version: '3.3'

services:
    db:
        image: mysql:5.7
        container_name: baita_sorte_db
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3308:3308"
        volumes:
            - ./run/var:/var/lib/mysql
            - ./docker-files/mysql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_TCP_PORT: 3308
        networks:
            - baita-sorte-network
    api:
        build:
            context: '.'
            dockerfile: Dockerfile
        container_name: baita-sorte-api
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        networks:
            - baita-sorte-network
        links:
            - db
networks:
    baita-sorte-network:
        driver: bridge